export const FETCH_ORDER_STATUS_REQUEST = 'FETCH_ORDER_STATUS_REQUEST';
export const FETCH_ORDER_STATUS_SUCCESS = 'FETCH_ORDER_STATUS_SUCCESS';
export const FETCH_ORDER_STATUS_FAILURE = 'FETCH_ORDER_STATUS_FAILURE';
