export const FETCH_PRODUCT_TYPE_REQUEST = 'FETCH_PRODUCT_TYPE_REQUEST';
export const FETCH_PRODUCT_TYPE_SUCCESS = 'FETCH_PRODUCT_TYPE_SUCCESS';
export const FETCH_PRODUCT_TYPE_FAILURE = 'FETCH_PRODUCT_TYPE_FAILURE';
