export const FETCH_ORDER_TYPE_REQUEST = 'FETCH_ORDER_TYPE_REQUEST';
export const FETCH_ORDER_TYPE_SUCCESS = 'FETCH_ORDER_TYPE_SUCCESS';
export const FETCH_ORDER_TYPE_FAILURE = 'FETCH_ORDER_TYPE_FAILURE';
